### ISSUE TITLE
Socket support

### ISSUE THREAD

**Issue by Azzeccagarbugli** [tgarm/flutter-luavm#1]
Thanks a lot for this wonderful project first of all!

I really would love to see an implementation of the standard library socket, so that I could use the `require 'socket'` in my code.

Let me know and thanks in advance, cheers!

**Comment by tgarm** [comment]
Sorry for late response. Currently I'm considering two way to implement this:
1. To implement async call to Dart so that Socket connection can be done in Dart.
2. To support LuaSocket natively, then each call to Lua script may run for a longer time.

Which way do you prefer?

**Comment by Azzeccagarbugli** [comment]
Actually this depends totally on you, I mean I tried to analyse the project but I didn't have too time unfortunately so I can't suggest you which way to take.

Maybe the approach in Dart is safer and more stable, but then is not so _native_ considering Lua, but still could be a nice workaround. Instead on the other side the Lua implementation could be easier but as you said, no as faster as the one in Dart.

Finally I think that both are pretty fine, and I thank you in advance!

**Comment by tgarm** [comment]
A Lua module __vmplugin__ has been added in 0.3.0. It contains __invoke\_method__ to call Dart code and more.
A simple http get example is now in the example project.
