### ISSUE TITLE
Could we return dart object to lua script

### ISSUE THREAD

**Issue by winterdl** [tgarm/flutter-luavm#2]
Hello,

Could we coerce dart object to lua script like Luaj:

LuaValue v = CoerceJavaToLua.coerce(new SampleClass());

Thanks.

**Comment by tgarm** [comment]
Thank you for your suggestion.

Could you describe it in more detail?

**Comment by winterdl** [comment]
Suppose I want to call methods or properties of Java object created from BufferedImage class, from Lua script, I could do something like the code below:

`Globals globals = JsePlatform.standardGlobals();   
globals.set("image", CoerceJavaToLua.coerce(
        new BufferedImage(30,40,BufferedImage.TYPE_INT_RGB)));
LuaValue chunk = globals.load(
        "print(image:getWidth(), image:getHeight());");
chunk.call();`

And in the Lua script I could call image:getWidth or image:getHight() of the object registered with engine. all public members from methods to properties of the object, I could call from Lua script.

Ref: https://stackoverflow.com/questions/33165577/luaj-what-does-coercejavatolua-do-with-a-java-object

**Comment by tgarm** [comment]
It seems a good feature, but somehow platform specific. 
Need to check the corresponding interface in other platform, currently just __iOS__
